services:
  backend-1:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2026-dotnet-csharp-with-faiss-interop:20260517214739
    hostname: backend-1
    volumes:
      - sock:/run/sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LISTEN_SOCK=/run/sock/api-1.sock
    cpuset: "0,1"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"
  backend-2:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2026-dotnet-csharp-with-faiss-interop:20260517214739
    hostname: backend-2
    volumes:
      - sock:/run/sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LISTEN_SOCK=/run/sock/api-2.sock
    cpuset: "2,3"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"
  load-balancer:
    image: haproxy:3.2.4-alpine
    volumes:
      - sock:/run/sock
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    cpuset: "0,2"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"